# Generated by Django 4.1.5 on 2023-01-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopform',
            new_name='shopmodel',
        ),
    ]
