# Generated by Django 4.1.5 on 2023-01-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_rename_shopform_shopmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopmodel',
            old_name='em',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shopmodel',
            old_name='ps',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='ulogmodel',
            old_name='em',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ulogmodel',
            old_name='ps',
            new_name='password',
        ),
    ]
