# Generated by Django 4.1.5 on 2023-01-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_shopregmodel_delete_shopmodel_delete_ulogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopregmodel',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='shopregmodel',
            old_name='name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='shopregmodel',
            old_name='password',
            new_name='spassword',
        ),
    ]
