# Generated by Django 4.1.5 on 2023-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_rename_email_shopregmodel_semail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='eapp/static')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
