# Generated by Django 4.1.5 on 2023-02-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmodel',
        ),
    ]
